apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-health
  labels:
    app: weather-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-health
  template:
    metadata:
      labels:
        app: weather-health
    spec:
      containers:
      - name: weather-health
        image: weather-health:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
